### ISSUE TITLE
0.12.0 not working with gulp-handlebars, 0.11.0 works fine

### ISSUE THREAD

**Issue by qodesmith** [adamayres/gulp-wrap#28]
I [raised an issue](https://github.com/lazd/gulp-handlebars/issues/74) over at the `gulp-handlebars` repo. They give the following example in their documentation which makes use of `gulp-wrap`:

```
gulp.task('templates', function(){
  gulp.src('source/templates/*.hbs')
    .pipe(handlebars({
      handlebars: require('handlebars')
    }))
    .pipe(wrap('Handlebars.template(<%= contents %>)'))
    .pipe(declare({
      namespace: 'MyApp.templates',
      noRedeclare: true, // Avoid duplicate declarations
    }))
    .pipe(concat('templates.js'))
    .pipe(gulp.dest('build/js/'));
});
```

I've been using `gulp-handlebars` 4.0.0, `handlebars` 4.0.5, and `gulp-wrap` 0.11.0 together for a while now. Everything plays nice. Just started a new project with the above and `gulp-wrap` 0.12.0 and I got the following error:

```
{ [TypeError: tmpl is not a function]
  name: 'TypeError',
  message: 'tmpl is not a function',
  stack: 'TypeError: tmpl is not a function\n
    at /Users/aaron.cordova/Projects/Sandbox/walmart-search/node_modules/consolidate/lib/consolidate.js:779:16\n
    at /Users/aaron.cordova/Projects/Sandbox/walmart-search/node_modules/consolidate/lib/consolidate.js:143:5\n
    at Promise._execute (/Users/aaron.cordova/Projects/Sandbox/walmart-search/node_modules/bluebird/js/release/debuggability.js:272:9)\n
    at Promise._resolveFromExecutor (/Users/aaron.cordova/Projects/Sandbox/walmart-search/node_modules/bluebird/js/release/promise.js:473:18)\n
    at new Promise (/Users/aaron.cordova/Projects/Sandbox/walmart-search/node_modules/bluebird/js/release/promise.js:77:14)\n
    at promisify (/Users/aaron.cordova/Projects/Sandbox/walmart-search/node_modules/consolidate/lib/consolidate.js:136:10)\n
    at Function.exports.lodash.render (/Users/aaron.cordova/Projects/Sandbox/walmart-search/node_modules/consolidate/lib/consolidate.js:775:10)\n
    at /Users/aaron.cordova/Projects/Sandbox/walmart-search/node_modules/gulp-wrap/index.js:73:37\n
    at process._tickCallback (node.js:401:9)',
  showStack: false,
  showProperties: true,
  plugin: 'gulp-wrap' }
```

Just wanted to make your team aware. Thanks.

**Comment by maxname** [comment]
I have same error. Yesterday worked fine.
